### ISSUE TITLE
Not seeing all objects  0.1.0-alpha.1

### ISSUE THREAD

**Issue by bostjanles** [martonsagi/al-object-designer#37]
In one workspace I see only 10 object out of 120. In other everything is OK.

Some al files are in root, some in src folder and some in third folder. Any all (2) files from root are included, all (2) from src subfolders, and only 6 from EOP_PI foder. This is temporary folder used for upgrading from CAL. 

![image](https://user-images.githubusercontent.com/9404581/68570856-e21b4c00-0461-11ea-90cf-6e42fea10702.png)

**Comment by martonsagi** [comment]
Thanks for the details. 

* Do you use a vscode `.workspace file` or the root directory is opened directly?
* Does the root directory contains multiple AL projects?

**Comment by bostjanles** [comment]
> 
> 
> Thanks for the details.
> 
>     * Do you use a vscode `.workspace file` or the root directory is opened directly?
> 
>     * Does the root directory contains multiple AL projects?

1. root is open directly
2. in root directory and all subfolders only one project.

**Comment by martonsagi** [comment]
Tried replicating the file layout, it seems to be working in my case.
Can you test with this folder: https://github.com/martonsagi/issue37-DepartmentsApp ?

There are AL files in the following places:
* Root folder
* Under `src` folder
* Under `Departments` folder

All objects are listed correctly.

Would you also send me the output from `Help -> Toggle Developer Tools` ? 

Thanks

**Comment by bostjanles** [comment]
Yours files are ok, here is output for my files

console.ts:137 [Extension Host] Extension "crs-al-language-extension" is now activated!
console.ts:137 [Extension Host] Running: SetupSnippets
console.ts:137 [Extension Host] Done: SetupSnippets
2console.ts:137 [Extension Host] (node:15580) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:137
2console.ts:137 [Extension Host] (node:15580) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
t.log @ console.ts:137
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
22webviewElement.ts:241 [Embedded Page] DEBUG [aurelia]
106webviewElement.ts:241 [Embedded Page] DEBUG [templating]
webviewElement.ts:241 [Embedded Page] INFO [aurelia]
webviewElement.ts:241 [Embedded Page] DEBUG [templating]
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'document' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'document' of undefined
	at Object.toggleRunObjectFromStatusBar (c:\Users\Boštjan\.vscode\extensions\waldo.crs-al-language-extension-1.1.21\out\UI\CRSStatusBar.js:7:54)
	at HandleOnOpenTextDocument (c:\Users\Boštjan\.vscode\extensions\waldo.crs-al-language-extension-1.1.21\out\CRSFunctions.js:149:18)
	at l.fire (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:545:768
	at l.fire (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at p.$acceptDocumentsAndEditorsDelta (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:549:927)
	at f._doInvokeHandler (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:646:285)
	at f._invokeHandler (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:645:999)
	at f._receiveRequest (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:664)
	at f._receiveOneMessage (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:477)
	at c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:641:754
	at l.fire (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at _.fire (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:274)
	at c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:798:104
	at l.fire (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at _.fire (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:274)
	at t.PersistentProtocol._receiveMessage (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:629)
	at c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:824
	at l.fire (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at f.acceptChunk (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:184:737)
	at c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:184:89
	at Socket.t (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:193:68)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
log.ts:196   ERR Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at asHoverContent (c:\Users\Boštjan\.vscode\extensions\ms-dynamics-smb.al-4.0.198182\node_modules\vscode-languageclient\lib\protocolConverter.js:101:27)
	at asHover (c:\Users\Boštjan\.vscode\extensions\ms-dynamics-smb.al-4.0.198182\node_modules\vscode-languageclient\lib\protocolConverter.js:134:31)
console.ts:137 [Extension Host] Running: HandleOnSaveTextDocument
console.ts:137 [Extension Host] Done: HandleOnSaveTextDocument
log.ts:196   ERR Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at asHoverContent (c:\Users\Boštjan\.vscode\extensions\ms-dynamics-smb.al-4.0.198182\node_modules\vscode-languageclient\lib\protocolConverter.js:101:27)
	at asHover (c:\Users\Boštjan\.vscode\extensions\ms-dynamics-smb.al-4.0.198182\node_modules\vscode-languageclient\lib\protocolConverter.js:134:31)
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
log.ts:196   ERR Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at asHoverContent (c:\Users\Boštjan\.vscode\extensions\ms-dynamics-smb.al-4.0.198182\node_modules\vscode-languageclient\lib\protocolConverter.js:101:27)
	at asHover (c:\Users\Boštjan\.vscode\extensions\ms-dynamics-smb.al-4.0.198182\node_modules\vscode-languageclient\lib\protocolConverter.js:134:31)
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
2log.ts:196   ERR Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at asHoverContent (c:\Users\Boštjan\.vscode\extensions\ms-dynamics-smb.al-4.0.198182\node_modules\vscode-languageclient\lib\protocolConverter.js:101:27)
	at asHover (c:\Users\Boštjan\.vscode\extensions\ms-dynamics-smb.al-4.0.198182\node_modules\vscode-languageclient\lib\protocolConverter.js:134:31)
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
log.ts:196   ERR Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at asHoverContent (c:\Users\Boštjan\.vscode\extensions\ms-dynamics-smb.al-4.0.198182\node_modules\vscode-languageclient\lib\protocolConverter.js:101:27)
	at asHover (c:\Users\Boštjan\.vscode\extensions\ms-dynamics-smb.al-4.0.198182\node_modules\vscode-languageclient\lib\protocolConverter.js:134:31)
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
4log.ts:196   ERR Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at asHoverContent (c:\Users\Boštjan\.vscode\extensions\ms-dynamics-smb.al-4.0.198182\node_modules\vscode-languageclient\lib\protocolConverter.js:101:27)
	at asHover (c:\Users\Boštjan\.vscode\extensions\ms-dynamics-smb.al-4.0.198182\node_modules\vscode-languageclient\lib\protocolConverter.js:134:31)
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
6log.ts:196   ERR Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at asHoverContent (c:\Users\Boštjan\.vscode\extensions\ms-dynamics-smb.al-4.0.198182\node_modules\vscode-languageclient\lib\protocolConverter.js:101:27)
	at asHover (c:\Users\Boštjan\.vscode\extensions\ms-dynamics-smb.al-4.0.198182\node_modules\vscode-languageclient\lib\protocolConverter.js:134:31)
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
log.ts:190  WARN Aborted format on save after 750ms
console.ts:137 [Extension Host] Running: HandleOnSaveTextDocument
console.ts:137 [Extension Host] Done: HandleOnSaveTextDocument
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
7log.ts:196   ERR Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at asHoverContent (c:\Users\Boštjan\.vscode\extensions\ms-dynamics-smb.al-4.0.198182\node_modules\vscode-languageclient\lib\protocolConverter.js:101:27)
	at asHover (c:\Users\Boštjan\.vscode\extensions\ms-dynamics-smb.al-4.0.198182\node_modules\vscode-languageclient\lib\protocolConverter.js:134:31)
log.ts:190  WARN Aborted format on save after 750ms
console.ts:137 [Extension Host] Running: HandleOnSaveTextDocument
console.ts:137 [Extension Host] Done: HandleOnSaveTextDocument
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Running: HandleOnSaveTextDocument
console.ts:137 [Extension Host] Done: HandleOnSaveTextDocument
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Running: HandleOnSaveTextDocument
console.ts:137 [Extension Host] Done: HandleOnSaveTextDocument
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Running: HandleOnSaveTextDocument
console.ts:137 [Extension Host] Done: HandleOnSaveTextDocument
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Running: HandleOnSaveTextDocument
console.ts:137 [Extension Host] Done: HandleOnSaveTextDocument
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Done: HandleOnOpenTextDocument
console.ts:137 [Extension Host] Running: HandleOnSaveTextDocument
console.ts:137 [Extension Host] Done: HandleOnSaveTextDocument
console.ts:137 [Extension Host] Running: HandleOnOpenTextDocument
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'document' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'document' of undefined
	at Object.toggleRunObjectFromStatusBar (c:\Users\Boštjan\.vscode\extensions\waldo.crs-al-language-extension-1.1.21\out\UI\CRSStatusBar.js:7:54)
	at HandleOnOpenTextDocument (c:\Users\Boštjan\.vscode\extensions\waldo.crs-al-language-extension-1.1.21\out\CRSFunctions.js:149:18)
	at l.fire (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:545:768
	at l.fire (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at p.$acceptDocumentsAndEditorsDelta (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:549:927)
	at f._doInvokeHandler (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:646:285)
	at f._invokeHandler (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:645:999)
	at f._receiveRequest (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:664)
	at f._receiveOneMessage (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:477)
	at c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:641:754
	at l.fire (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at _.fire (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:274)
	at c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:798:104
	at l.fire (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at _.fire (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:274)
	at t.PersistentProtocol._receiveMessage (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:629)
	at c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:824
	at l.fire (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at f.acceptChunk (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:184:737)
	at c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:184:89
	at Socket.t (c:\Users\Boštjan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:193:68)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
22webviewElement.ts:241 [Embedded Page] DEBUG [aurelia]
106webviewElement.ts:241 [Embedded Page] DEBUG [templating]
webviewElement.ts:241 [Embedded Page] INFO [aurelia]
webviewElement.ts:241 [Embedded Page] DEBUG [templating]

**Comment by martonsagi** [comment]
Thanks, it's a great mystery then. :)

I have created a new alpha build with some additional settings that might help us getting closer to the solution.
[0.1.0-alpha.2](https://github.com/martonsagi/al-object-designer/blob/0.1.0-dev/custom-builds/al-object-designer-0.1.0-alpha.2.vsix)

New options:
* **Logging:** default is true. It shows information about detected files and symbols in Developer Tools
* **Single object per file:** default is false. This is a fallback option to use the old object header parsing method.

![image](https://user-images.githubusercontent.com/18100709/68630242-f7868980-04e6-11ea-9e6f-88f566e51013.png)

In Developer Tools, please filter to `al-object-designer`
![image](https://user-images.githubusercontent.com/18100709/68630654-42ed6780-04e8-11ea-95bd-a2dd54fe386c.png)

Can you try with **Single object per file** on/off and send the filtered output from Developer Tools?
Thanks!

**Comment by martonsagi** [comment]
And the most obvious question I missed: did it work in 0.0.7 (Marketplace version)? :)

**Comment by bostjanles** [comment]
> 
> 
> And the most obvious question I missed: did it work in 0.0.7 (Marketplace version)? :)

Just tested with 0.0.7 and it is the same problem.

I will try new alpha during the day.

**Comment by bostjanles** [comment]
Me back :-)

I tried new alpha. With default setting, there was no change, but then I set "Single Object Per File" and is working :-)
Logs for TRUE/FALSE
[OneObjectPerFile_TRUE.txt](https://github.com/martonsagi/al-object-designer/files/3845208/OneObjectPerFile_TRUE.txt)
[OneObjectPerFile_FALSE.txt](https://github.com/martonsagi/al-object-designer/files/3845209/OneObjectPerFile_FALSE.txt)

**Comment by martonsagi** [comment]
Thanks for the updates.

I believe there was an issue with multi-object/file recognition that caused all of this. Got it fixed in [0.1.0-alpha.4](https://github.com/martonsagi/al-object-designer/blob/0.1.0-dev/custom-builds/al-object-designer-0.1.0-alpha.4.vsix).

The expected result should be the same with "Single Object Per File" turned off. (Except if you have multiple objets in one file, then you should see more objects in the list. :) )

**Comment by bostjanles** [comment]
No, it still not working.

**Comment by martonsagi** [comment]
Can you send me some object headers that are not visible on the list? 
I need only the first lines to test with regular expressions, not source code. Just like `page 70000 xxx_object`. 

If not here, perhaps via LinkedIn. Thanks!

**Comment by bostjanles** [comment]
Check LinkedIn

**Comment by martonsagi** [comment]
Thanks for the example project. Did some fixes and tested with [0.1.0-beta.1](https://github.com/martonsagi/al-object-designer/blob/0.1.0-dev/custom-builds/al-object-designer-0.1.0-beta.1.vsix)
44 out of 44 AL files were shown in the object list. 

Please check it, I'm hoping this version will solve the issue.

Thanks!

**Comment by martonsagi** [comment]
Left out objects have uppercase starting characters, but the regular expression wasn't set to case-insensitive. Hence the missing objects.
Added a new build that should be working with the other example project source.

[0.1.0-beta.2](https://github.com/martonsagi/al-object-designer/blob/0.1.0-dev/custom-builds/al-object-designer-0.1.0-beta.2.vsix)

**Comment by bostjanles** [comment]
It worx :-)

**Comment by martonsagi** [comment]
Perfect, thank you for your help!
